#spring.application.name=Ecommerce
#
## ===============================
## MySQL Database Configuration
## ===============================
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#
## ===============================
## JWT Configuration
## ===============================
#spring.app.jwtSecret=${JWT_SECRET}
#spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
#spring.ecom.app.jwtCookieName=${JWT_COOKIE_NAME}
#
## ===============================
## Frontend / CORS
## ===============================
#frontend.url=${FRONTEND_URL}
#
## ===============================
## Image Configuration
## ===============================
#product.image=images/
#image.base.url=${IMAGE_BASE_URL}
#
## ===============================
## Stripe Configuration
## ===============================
#stripe.secret.key=${STRIPE_SECRET_KEY}
#
## ===============================
## Logging (optional – dev only)
## ===============================
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.Ecommerce.Project=DEBUG
#

server.port=8080
spring.profiles.active=${ENV:dev}



#
#
## ===============================
## Database Configuration
## ===============================
#DB_URL=jdbc:mysql://localhost:3306/ecommerce
#DB_USERNAME=root
#DB_PASSWORD=Arsh@1106
#; DB_DRIVER=com.mysql.cj.jdbc.Driver
#
## ===============================
## JWT Configuration
## ===============================
#JWT_SECRET=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
#JWT_COOKIE_NAME=jwtCookieName
#JWT_EXPIRATION_MS=3000000
#
## ===============================
## Frontend Configuration
## ===============================
#FRONTEND_URL=http://localhost:5173
#
## ===============================
## Image Configuration
## ===============================
#IMAGE_BASE_URL=http://localhost:8080/images
#
## ===============================
## Stripe Configuration
## ===============================
#STRIPE_SECRET_KEY=sk_test_51SIojJCwifQ8ptbASGvg8WuOLiPJEDjU4zCWI5lnHMkY2ylVvly2SJOCs6wFqU0x2Uw1r6DceieZ4cUk8W0jXJzm00maJpN3wy
#
#
#
#
