spring.application.name=Ecommerce

#it enables your h2-database localhost URL:---->>>>
#spring.h2.console.enabled=true
#it makes your jdbc url fixed so that on every run and stop
# you dont need to change your URL
#spring.datasource.url=jdbc:h2:mem:test

#these two property help in generating sql-query related to working and will show us
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


#ddl-auto batata hai ki Hibernate database schema (tables/columns) ko kaise handle kare:
#none -> kuch bhi auto create/update nahi karega (default in production).
#validate -> sirf check karega ki aapki entities aur database schema match karte hain ya nahi.
#update -> agar entity me naye fields/mapping add karte ho to woh database table me column bhi add kar dega (data lose nahi hota).
#create -> har baar app start hote hi pura schema naya create karega (purana data delete ho jayega).
#create-drop -> start pe create hoga, aur app band hone pe drop ho jayega.


#spring.jpa.hibernate.dl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=Arsh@1106
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true


#this configuration is for my-sql database
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=Arsh@1106
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#mysql://root:NMaBrEpJmnIVyopfrAVlAkZZbAvFOTCW@mysql.railway.internal:3306/railway
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=YSExTAZNJfjdwszBqIhOXqhkujfrLEqV
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect



#spring.datasource.url=jdbc:postgresql://yamabiko.proxy.rlwy.net:26866/railway?sslmode=require
#spring.datasource.username=postgres
#spring.datasource.password=HDQPiPAVqPRPFkjVQEfyAAgiPWIKNjDz
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true



#needed if you are using beanstalk with aws
#server.port=5001
#server.port=${PORT:5001}
#server.port=${PORT:8080}





spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName=springBootEcom
product.image=images/


logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.Ecommerce.Project=DEBUG



